#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: cimg/ruby:3.0.6-node
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            gem install -n /usr/local/bin jekyll

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build site
          command: |
            - ./vendor/bundle
            jekyll build

      # Deploy 
      - deploy:     
          name: Deploy to website
          command: |
            ssh -o StrictHostKeyChecking=no -p$DEPLOY_REMOTE_PORT $DEPLOY_USER@$DEPLOY_REMOTE /admin/bin/rmVarHtml.sh
            echo "copying new"
            scp -o StrictHostKeyChecking=no -r -P$DEPLOY_REMOTE_PORT ~/repo/_site/* $DEPLOY_USER@$DEPLOY_REMOTE:/var/www/html/	
            echo "copying files"
            ssh -o StrictHostKeyChecking=no -p$DEPLOY_REMOTE_PORT $DEPLOY_USER@$DEPLOY_REMOTE "mkdir -p /var/www/html/files/"
            scp -o StrictHostKeyChecking=no -r -P$DEPLOY_REMOTE_PORT ~/repo/files/.htaccess $DEPLOY_USER@$DEPLOY_REMOTE:/var/www/html/files/.htaccess
            scp -o StrictHostKeyChecking=no -r -P$DEPLOY_REMOTE_PORT ~/repo/files/* $DEPLOY_USER@$DEPLOY_REMOTE:/var/www/html/files/	

